# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=10)),
                ('date_taken', models.DateTimeField(verbose_name='date taken')),
            ],
        ),
    ]
